<?php

// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BrlReCaptcha\ReCaptcha'                => __DIR__.'/src/BrlReCaptcha/ReCaptcha.php',
    'BrlReCaptcha\Service\ReCaptchaService' => __DIR__.'/src/BrlReCaptcha/Service/ReCaptchaService.php',
    'BrlReCaptcha\Helper\ReCaptcha'         => __DIR__.'/src/BrlReCaptcha/Helper/ReCaptcha.php',
    'BrlReCaptcha\Module'                   => __DIR__.'/Module.php',
);
